### PR TITLE
52 setup express skeleton

### PR DESCRIPTION
**Pull request by systm-spec**
~ barebones set

### CODE REVIEW

**Comment by systm-spec** [comment]
Changes made and tested

**Comment by ReallyBoard123** [comment]
Hey Felix, things are still very confusing. 
I cannot understand the folder structure. What happened to all those files that were deleted?
for example, where is our tailwind config?

Screenshot 2023-07-14 100935

Also, I cannot understand why do we have a Prisma schema there. Which part of the issue asks to setup Prisma?

**Review by ReallyBoard123 — CHANGES_REQUESTED** [review]
No.

**Comment by systm-spec** [comment]
Removed anyth but server/http for test for clean merge.
Removed Prisma, including changes to controller.

**Comment by systm-spec** [comment]
@ReallyBoard123 
New PR #64  with new branch so stuff won't get messed up even more =P

**Pull request closed without merging**
