### PR TITLE
38 create genre overview

### LINKED ISSUE #38: Create Genre Overview
This page is reached when the user clicks on the "See All" link on the genre section on the homepage to select genres from a list of genres. Earlier, this was intended to be a full-page modal but later changed to a page layout for ease. You are still free to choose whichever route you are comfortable with.

When the user selects the genre, 1 ) the upcoming movie section on the home page, and 2) the movies page for now_playing will show only the movies from the selected genre

## Prerequisites 
- [x] #9 

## Tasks

- [x] Create an object that maps emojis to genres
- [x] Make each IconButton selectable
- [x] When selected is clicked again -> deselect
- [x] keep a count of selected genres

## Hints

The current API already has a list of genres. They have some 15 listed. We will only be using 12 of them. Check the ones that are missing. Each genre would have an id, an emoji, and a name.

Should the selected genre be persisted via a global store?

## Figma Resources
https://www.figma.com/file/TOCJzJFMXE7PL1dQyGWqXZ/midterm?type=design&node-id=18%3A560&mode=design&t=poNoiZC2HH4cKdlU-1

### PR DESCRIPTION
**Pull request by pswu11**
closes #38 

- add genres-store and make it persistent
- add genres page

### CODE REVIEW

**Comment by pswu11** [comment]
Hi @ReallyBoard123 I would like to suggest simplifying GenreIcon's properties (see codes in PR) as it'd be easier to work with. But let me know if the original design should be kept.

**Review by ReallyBoard123 — CHANGES_REQUESTED** [review]
Sorry for this late update:
I had a word with senior on this particular feature, and they requested the following changes:

1. The current architecture of storing the information in an array could be difficult to manage. It was suggested to rather use an object with appropriate keys. 

2. The home genreIcons should also be dynamic. According to design we currently render only 4 icons on the home page(fixed to: Romance, Comedy, Horror, Drama). As initial genres these should be okay. But when the user goes to /genres page, and selects some icons there, we want the home to dynamically display those rather than the initial ones. If the user has selected less than 4, than it should display those first, and then fill up the genreicon on the home page with the initial ones.

3. we do not need to persist the store beyond the session.

4. The store should reset back to false state, if the user did not click on "confirm button" on the genres page

**Comment by ReallyBoard123** [comment]
Check `refactor-genres-overview` branch for a working example of some of these requested changes. 
Additionally, you could also move the genreIcon from zustand to `lib/genreLibrary` .

- The type for genreIcon are currently not being reused. Perhaps check that as well!

Thankyou!! Great effort from the two of you.

**Review by ReallyBoard123 — APPROVED** [review]
👍 congratulations!

**Pull request merged**
